### ISSUE TITLE
Are you really meant to be a public repository?

### ISSUE THREAD

**Issue by oliverlockwood** [sky-uk/cezanne#13]
We have noticed this repository was marked as public.  There are certain standards required before a repository in the `sky-uk` org can be made public, including the presence of valid `LICENSE.md`, `README.md`, and `CONTRIBUTING.md` files.
-  Repos without license information are immediately made private.
-  Repos failing the other criteria will be made private after 30 days.

Please resolve these problems ASAP and close this GitHub issue when you have done so.

If you have any questions, please ask them on the #github Slack channel.

**Comment by pigats** [comment]
Hi @oliverlockwood, thanks for your interest.

Cezanne was made public quite a long time ago, with the approval (if I remember correctly) of principal engineer @behaghel

You can find all the pieces of information you referred to:
- readme: https://github.com/sky-uk/cezanne/blob/master/README.md
- license: https://github.com/sky-uk/cezanne/blob/master/LICENSE
- how to contribute: https://github.com/sky-uk/cezanne#contributing

I'm going to close the issue, but if you think the repo doesn't meet the requirements, please reopen the issue and point me to the guidelines. 

Best :)

**Comment by behaghel** [comment]
To add to this, this received explicit approval from Andy Burton, Director of Sales and Service at that time.

**Comment by oliverlockwood** [comment]
Hi @pigats @behaghel thanks for getting back to me.  It sounds like you've done all the right things.  I'm gonna send you a PM on Slack shortly.

**Comment by oliverlockwood** [comment]
Reopening this as discussed, until `CONTRIBUTING.md` is added :smiley:

**Comment by pigats** [comment]
whoops, the references here don't play nice with `rebase`
